// ─── Mock users ───────────────────────────────────────────────────────────────
export const MOCK_USERS = [
  { id: 1, email: 'mariana@levva.io',  name: 'Mariana Thomaz'   },
  { id: 2, email: 'lucas@levva.io',    name: 'Lucas Ferreira'   },
  { id: 3, email: 'ana@levva.io',      name: 'Ana Paula Santos' },
  { id: 4, email: 'rafael@levva.io',   name: 'Rafael Oliveira'  },
  { id: 5, email: 'camila@levva.io',   name: 'Camila Costa'     },
  { id: 6, email: 'bruno@levva.io',    name: 'Bruno Mendes'     },
  { id: 7, email: 'julia@levva.io',    name: 'Julia Rodrigues'  },
]

// ─── Scores por usuário (pillar_id 1-28) ──────────────────────────────────────
// Estrutura: email -> { pillar_id: { score, evidence?, goal? } }
export const MOCK_EVALUATIONS = {

  'mariana@levva.io': {
    1:  { score: 4, evidence: 'Reestruturei a IA do app de pagamentos, aumentando a conclusão de tarefas em 23%.', goal: 'Aprofundar em taxonomias para produtos financeiros complexos.' },
    2:  { score: 4, evidence: 'Liderei o redesign do onboarding com protótipos de alta fidelidade no Figma.' },
    3:  { score: 4, evidence: 'Mantemos um DS com 80+ componentes usados por 3 produtos simultaneamente.' },
    4:  { score: 3, goal: 'Melhorar minha documentação de handoff com mais especificações de estados.' },
    5:  { score: 4, evidence: 'Conduzi 12 entrevistas com usuários e sintetizei em relatório de achados.' },
    6:  { score: 3, goal: 'Aprender a cruzar dados qualitativos com analytics do GA4.' },
    7:  { score: 4, evidence: 'Criei blueprint de serviço completo para jornada de crédito consignado.' },
    8:  { score: 3 },
    9:  { score: 5, evidence: 'Facilitei 3 Design Sprints com squads multidisciplinares, gerando backlog priorizado.' },
    10: { score: 4, evidence: 'Conduzo kickoffs e retrospectivas mensais de design.' },
    11: { score: 4, evidence: 'Apresentei resultados de discovery para C-level do cliente sem perder profundidade.' },
    12: { score: 3, goal: 'Estruturar mentorias formais com designers juniores da equipe.' },
    13: { score: 4, evidence: 'Definimos North Star Metric e métricas de produto para 2 iniciativas do cliente.' },
    14: { score: 3 },
    15: { score: 4, evidence: 'Negociei escopo de entrega com PO, mantendo qualidade sem atrasar sprint.' },
    16: { score: 3, goal: 'Contribuir com artigo no blog da Levva sobre pesquisa com usuários.' },
    17: { score: 5, evidence: 'Uso IA generativa diariamente: Midjourney para conceitos, Claude para síntese de pesquisa.' },
    18: { score: 4, evidence: 'Projetei interface de chat com IA para assistente de investimentos.' },
    19: { score: 3 },
    20: { score: 3, goal: 'Criar checklist de ética em IA para projetos do time.' },
    21: { score: 4, evidence: 'Mapeei stakeholders do cliente e adaptei minha abordagem para cada perfil.' },
    22: { score: 4, evidence: 'Gerencio expectativas via status semanal e rituais de alinhamento.' },
    23: { score: 3 },
    24: { score: 4, evidence: 'Identifiquei oportunidade de upsell ao mapear gap de experiência no pós-venda.' },
    25: { score: 4, evidence: 'Organizo sprints no Jira com épicos, histórias e critérios de aceite claros.' },
    26: { score: 3 },
    27: { score: 4, evidence: 'Criei template de handoff adotado por todo o time de design da conta.' },
    28: { score: 4, evidence: 'Auditei acessibilidade de 3 fluxos críticos e corrigi 14 violações WCAG AA.' },
  },

  'lucas@levva.io': {
    1:  { score: 3 },
    2:  { score: 4, evidence: 'Excelência em Figma: componentização avançada com variants e auto-layout.' },
    3:  { score: 3 },
    4:  { score: 3 },
    5:  { score: 5, evidence: 'Conduzi pesquisa longitudinal de 3 meses com 40 usuários de app de investimentos.' },
    6:  { score: 5, evidence: 'Cruzei dados do Hotjar, GA4 e entrevistas para identificar maior ponto de atrito.' },
    7:  { score: 4, evidence: 'Produzo jornadas e blueprints detalhados que viram referência no projeto.' },
    8:  { score: 4, evidence: 'Estruturei árvore de oportunidades e backlog com 30+ hipóteses priorizadas.' },
    9:  { score: 3 },
    10: { score: 3 },
    11: { score: 4, evidence: 'Storytelling eficaz: apresentações de pesquisa aprovadas sem revisão.' },
    12: { score: 3 },
    13: { score: 4, evidence: 'Defini métricas HEART para features de onboarding.' },
    14: { score: 3 },
    15: { score: 3 },
    16: { score: 4, evidence: 'Palestrante convidado em evento de UX Research interno da Levva.' },
    17: { score: 3 },
    18: { score: 2, goal: 'Me aprofundar em design para LLMs e interfaces conversacionais.' },
    19: { score: 3 },
    20: { score: 3 },
    21: { score: 3 },
    22: { score: 4, evidence: 'Comunicação clara e antecipada sobre riscos e mudanças de escopo.' },
    23: { score: 3 },
    24: { score: 3 },
    25: { score: 2, goal: 'Melhorar organização no Jira e criar padrão de nomenclatura.' },
    26: { score: 2, goal: 'Documentar processos de pesquisa para compartilhar com o time.' },
    27: { score: 3 },
    28: { score: 2, goal: 'Estudar WCAG e incluir acessibilidade como critério em todo projeto.' },
  },

  'ana@levva.io': {
    1:  { score: 4, evidence: 'Crio flows e wireframes com muita atenção à hierarquia visual.' },
    2:  { score: 3 },
    3:  { score: 4, evidence: 'Contribuí ativamente para o Design System da conta Fintech.' },
    4:  { score: 3 },
    5:  { score: 3 },
    6:  { score: 4, evidence: 'Cruzo feedback de suporte com dados de uso para validar hipóteses.' },
    7:  { score: 3 },
    8:  { score: 4, evidence: 'Uso canvas de UX e árvore de oportunidades para estruturar decisões.' },
    9:  { score: 5, evidence: 'Referência em facilitação: conduzi 8 workshops com times distribuídos.' },
    10: { score: 5, evidence: 'Extraio insights acionáveis de todas as dinâmicas e distribuo síntese ao time.' },
    11: { score: 5, evidence: 'Apresentações claras, visuais e com narrativa forte. Feedback excelente dos clientes.' },
    12: { score: 4, evidence: 'Faço onboarding de designers novos e conduzo 1:1s de desenvolvimento.' },
    13: { score: 3 },
    14: { score: 3 },
    15: { score: 4, evidence: 'Construo consenso com facilidade, mesmo em ambientes de alta pressão.' },
    16: { score: 3 },
    17: { score: 2, goal: 'Criar rotina de experimentos com ferramentas de IA no fluxo de trabalho.' },
    18: { score: 2, goal: 'Estudar cases de produtos com IA embarcada para me inspirar.' },
    19: { score: 3 },
    20: { score: 2 },
    21: { score: 4, evidence: 'Navego bem em estruturas corporativas complexas e sei influenciar sem autoridade.' },
    22: { score: 3 },
    23: { score: 4, evidence: 'Argumentação sólida: raramente tenho decisões de design questionadas sem base.' },
    24: { score: 3 },
    25: { score: 4, evidence: 'Uso Notion para organizar toda a documentação dos projetos.' },
    26: { score: 4, evidence: 'Criei biblioteca de componentes de pesquisa reutilizáveis.' },
    27: { score: 3 },
    28: { score: 4, evidence: 'Sempre incluo checklist de acessibilidade antes de qualquer entrega.' },
  },

  'rafael@levva.io': {
    1:  { score: 4, evidence: 'Referência técnica no time: código Figma limpo e componentizado.' },
    2:  { score: 5, evidence: 'Nível de acabamento visual dos meus projetos é consistentemente acima da média.' },
    3:  { score: 4, evidence: 'Arquitetei DS multi-produto com tokens e documentação completa.' },
    4:  { score: 4, evidence: 'Handoffs detalhados que eliminam retrabalho de dev.' },
    5:  { score: 4, evidence: 'Pesquisas bem estruturadas com rigor metodológico.' },
    6:  { score: 4, evidence: 'Triangulação de dados é meu ponto forte em discovery.' },
    7:  { score: 3 },
    8:  { score: 4, evidence: 'Backlog de produto estruturado e priorizado com clareza.' },
    9:  { score: 4, evidence: 'Boa facilitação, especialmente em sessões de ideação.' },
    10: { score: 3 },
    11: { score: 4, evidence: 'Apresentações executivas com narrativa clara e dados sólidos.' },
    12: { score: 4, evidence: 'Mentoro 2 designers juniores da conta.' },
    13: { score: 5, evidence: 'Lidero a definição de métricas de produto em todas as contas que atuo.' },
    14: { score: 4, evidence: 'Domínio profundo do mercado de fintechs e seus modelos de negócio.' },
    15: { score: 5, evidence: 'Influenciei decisões de roadmap sem autoridade formal em 3 ocasiões.' },
    16: { score: 4, evidence: 'Reconhecido pelo cliente como referência de design thinking.' },
    17: { score: 4, evidence: 'Uso IA para acelerar exploração conceitual e prototipação.' },
    18: { score: 3 },
    19: { score: 4, evidence: 'Integrei IA nos fluxos de pesquisa, reduzindo tempo de síntese em 40%.' },
    20: { score: 3 },
    21: { score: 4, evidence: 'Forte habilidade política: sei navegar em organizações complexas.' },
    22: { score: 4, evidence: 'Gerenciamento de expectativas proativo e transparente.' },
    23: { score: 4, evidence: 'Defendo decisões com dados e convicção.' },
    24: { score: 4, evidence: 'Identifico oportunidades de negócio além do escopo de design.' },
    25: { score: 4, evidence: 'Processos de projeto claros e visíveis para todos os stakeholders.' },
    26: { score: 3 },
    27: { score: 4, evidence: 'Fluxos de trabalho bem definidos e documentados.' },
    28: { score: 4, evidence: 'Acessibilidade como critério não-negociável nos meus projetos.' },
  },

  'camila@levva.io': {
    1:  { score: 3 },
    2:  { score: 4, evidence: 'Excelente senso estético e domínio de tipografia e cor.' },
    3:  { score: 3 },
    4:  { score: 3 },
    5:  { score: 3 },
    6:  { score: 3 },
    7:  { score: 4, evidence: 'Bons mapas de jornada, especialmente para fluxos digitais.' },
    8:  { score: 3 },
    9:  { score: 4, evidence: 'Facilitação energética e engajante.' },
    10: { score: 3 },
    11: { score: 3 },
    12: { score: 4, evidence: 'Compartilho aprendizados sobre IA semanalmente com o time.' },
    13: { score: 3 },
    14: { score: 3 },
    15: { score: 3 },
    16: { score: 4, evidence: 'Referência interna em design para IA na Levva.' },
    17: { score: 5, evidence: 'Domine o stack completo de IA generativa: Midjourney, Runway, Claude, ChatGPT, Cursor.' },
    18: { score: 5, evidence: 'Projetei 3 produtos com IA embarcada, incluindo um copiloto para investidores.' },
    19: { score: 5, evidence: 'Conduzo experimentação semanal com novas ferramentas e compartilho aprendizados.' },
    20: { score: 4, evidence: 'Criei framework de avaliação ética de IA adotado pelo time.' },
    21: { score: 2, goal: 'Desenvolver habilidade de navegação política em contextos de alta complexidade.' },
    22: { score: 3 },
    23: { score: 2, goal: 'Fortalecer capacidade de argumentação baseada em dados de negócio.' },
    24: { score: 3 },
    25: { score: 3 },
    26: { score: 3 },
    27: { score: 4, evidence: 'Processos ágeis bem implementados nos projetos que lidero.' },
    28: { score: 3 },
  },

  'bruno@levva.io': {
    1:  { score: 2, goal: 'Investir em estudos de layout e composição visual.' },
    2:  { score: 3 },
    3:  { score: 2, goal: 'Aprender Figma avançado: variantes, auto-layout e tokens.' },
    4:  { score: 3 },
    5:  { score: 3 },
    6:  { score: 4, evidence: 'Boa leitura de mercado e benchmarks competitivos.' },
    7:  { score: 3 },
    8:  { score: 3 },
    9:  { score: 4, evidence: 'Conduzo workshops executivos com segurança.' },
    10: { score: 3 },
    11: { score: 4, evidence: 'Excelente oratória e capacidade de adaptar linguagem ao público.' },
    12: { score: 3 },
    13: { score: 3 },
    14: { score: 3 },
    15: { score: 4, evidence: 'Habilidade política forte: construo alianças estratégicas com facilidade.' },
    16: { score: 3 },
    17: { score: 3 },
    18: { score: 3 },
    19: { score: 3 },
    20: { score: 2 },
    21: { score: 5, evidence: 'Referência em gestão de stakeholders: navego C-level com naturalidade.' },
    22: { score: 4, evidence: 'Gerencio projetos complexos com múltiplos stakeholders sem perder alinhamento.' },
    23: { score: 5, evidence: 'Fundamentação impecável: toda proposta vem com dados, benchmarks e ROI estimado.' },
    24: { score: 4, evidence: 'Histórico de identificar oportunidades de negócio nos projetos de UX.' },
    25: { score: 3 },
    26: { score: 4, evidence: 'Boa documentação e organização de repositórios de projeto.' },
    27: { score: 3 },
    28: { score: 3 },
  },

  'julia@levva.io': {
    1:  { score: 4, evidence: 'IA bem estruturada, sempre com foco em clareza e redução de carga cognitiva.' },
    2:  { score: 4, evidence: 'Design visual refinado com atenção especial a sistemas de grade.' },
    3:  { score: 3 },
    4:  { score: 4, evidence: 'Entregas técnicas com documentação completa e zero retrabalho.' },
    5:  { score: 3 },
    6:  { score: 4, evidence: 'Boa leitura de dados e capacidade de transformar números em insights.' },
    7:  { score: 4, evidence: 'Mapas de jornada detalhados e bem estruturados.' },
    8:  { score: 3 },
    9:  { score: 4, evidence: 'Boa facilitação com foco em resultado e tempo.' },
    10: { score: 4, evidence: 'Extraio muito valor das dinâmicas: sínteses claras e acionáveis.' },
    11: { score: 3 },
    12: { score: 4, evidence: 'Faço mentoria informal com designers do time.' },
    13: { score: 3 },
    14: { score: 4, evidence: 'Bom entendimento do modelo de negócio dos clientes.' },
    15: { score: 3 },
    16: { score: 4, evidence: 'Reconhecida pelos clientes como referência técnica.' },
    17: { score: 3 },
    18: { score: 3 },
    19: { score: 4, evidence: 'Integrei 5 ferramentas de IA no workflow do meu time.' },
    20: { score: 3 },
    21: { score: 4, evidence: 'Boa leitura de contexto organizacional e jogo político.' },
    22: { score: 4, evidence: 'Comunicação precisa sobre riscos e entregas.' },
    23: { score: 3 },
    24: { score: 4, evidence: 'Proativa em identificar oportunidades de melhoria além do escopo.' },
    25: { score: 5, evidence: 'Organização impecável: Notion, Jira e Figma sempre atualizados e acessíveis.' },
    26: { score: 5, evidence: 'Criei repositório de conhecimento do time: templates, guias e processos documentados.' },
    27: { score: 4, evidence: 'Fluxos de trabalho padronizados adotados em todas as contas.' },
    28: { score: 5, evidence: 'Referência em acessibilidade: auditei todos os produtos da conta e reduzi violações em 80%.' },
  },
}

// Retorna avaliações no formato esperado pela API (array de objetos)
export function getEvalsForEmail(email) {
  const evals = MOCK_EVALUATIONS[email]
  if (!evals) return []
  return Object.entries(evals).map(([pillar_id, data]) => ({
    pillar_id: Number(pillar_id),
    ...data,
  }))
}

// Retorna o usuário mock pelo email, ou cria um novo
export function getMockUser(email, name) {
  return MOCK_USERS.find(u => u.email === email) || { id: 99, email, name: name || email }
}
